# Основные настройки сайта
theme: minima
title: Nova Vertex Code
description: Unity Assets for Educational and Interactive Applications
url: "url: "https://novavertexcode.github.io/unity-assets" # Ваш базовый URL

# Настройки Minima
minima:
  skin: dark # Варианты: classic, dark, auto
  social_links:
    - { platform: github, user_url: "https://github.com/yourusername" }
    # Добавьте другие соцсети, если нужно (например, LinkedIn)

# Настройки Jekyll
markdown: kramdown
permalink: pretty # Чистые URL без .html
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Плагины
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Настройки для SEO
author:
  name: Nova Vertex Code
  email: nova.vertex.code@yandex.com